[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "codeium"]

[language-server.rust]
command = "rust-analyzer"
language-id = "rust"

[language-server.go]
command = "gopls"
language-id = "go"

[language-server.java]
command = "jdtls"
language-id = "java"

[language-server.zig]
command = "zls"
language-id = "zig"

# OmniSharp LSP for C#
[language-server.omnisharp]
command = "/usr/bin/omnisharp"
args = ["--languageserver"]

[[language]]
name = "c-sharp"
auto-format = true

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scala"
indent = { tab-width = 4, unit = "    " }
